.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH J7 1 "April 23, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
j7 \- An interpreter for the J language
.SH SYNOPSIS
.B j7
.RI [ options ] " files" ...
.br
.SH DESCRIPTION
This manual page documents briefly the
.B j7
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBj7\fP is a program that implements an interpreter for
the J computer language, a dialect of APL, both designed by
Kenneth Iverson.
.SH OPTIONS
\fBj7\fP takes only the an optional J script file argument to be preloaded.
There are no command flags.
.br
.SH AUTHOR
j7 was written by programmers at Jsoftware.com
.PP
This manual page was written by Don Barry <don@donbarry.org>,
for the Debian project (and may be used by others).
